
name: ZIP Sector
on: workflow_dispatch


jobs:
  zip:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Create source code structure
        run: |
          mkdir LLLL
          cp -r ISRAEL.clr LLLL.isc Include LLLL/
          cd LLLL
          zip -r LLLL.zip .
          zipinfo LLLL.zip

      - uses: actions/upload-artifact@v4
        with:
          name: LLLL
          path: LLLL/LLLL.zip