
name: ZIP Sector
#on: workflow_dispatch
# on:
#   release:
#     types: [published]
on: 
  push:
    # only trigger on branches, not on tags
    branches: 'gh-actions'


jobs:
  zip:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: ZIP files
        run: |
          mkdir LLLL
          cp -r ISRAEL.clr LLLL.isc Include LLLL/
          cd LLLL
          zip -r LLLL.zip .
          zipinfo LLLL.zip

      - uses: actions/upload-artifact@v4
        with:
          name: LLLL
          path: LLLL/LLLL.zip
          compression-level: 0

      - name: Release
        uses: softprops/action-gh-release@v2
        # if: github.ref_type == 'tag'
        with:
          files: LLLL/LLLL.zip