
name: ZIP Sector
on: workflow_dispatch


jobs:
  zip:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Create source code structure
        run: |
          ls -la
          mkdir LLLL
          cp -r ISRAEL.clr LLLL.isc Include LLLL/
          echo "ls -la"
          ls -la
          echo "ls -la LLLL"
          ls -la LLLL